import com.loan_application.loan_application_rules.Applicant;
import com.loan_application.loan_application_rules.Loan;
rule "Setting default values on Applicant"
	dialect "mvel"
	ruleflow-group "initialisation-rules"
	no-loop true
	when
		applicant : Applicant( )
	then
		System.out.println("Rule fired : [" + drools.getRule().getName()+"]");
		applicant.setEligible( true );
		applicant.setMonthlyIncome (applicant.getYearlyIncome()/12);
end

rule "Setting default values on Loan"
	dialect "mvel"
	ruleflow-group "initialisation-rules"
	no-loop true
	when
		loan : Loan( )
	then
		System.out.println("Rule fired : [" + drools.getRule().getName()+"]");
		loan.setApproved( false );
end